### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Shizu567** [Balackburn/YTLitePlus#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:
- Device model:
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):

### Describe the bug

Can you please add the Video Quality Select feature like uyou+, so that every video will play on the selected quality automatically.
And Also the gesture feature to control volume and brightness like uyou+

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
This is not a bug, but a feature request, I'm not a tweak developer, so I closed the issue, the YTLite developer said he would look into adding these features.
