### ISSUE TITLE
[Bug] Hide shorts does not work

### ISSUE THREAD

**Issue by MaartenSomay** [Balackburn/YTLitePlus#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: IOS 16.5.1
- Device model: Ip 14 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Esign
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 18.28.3_2.3

### Describe the bug

Even tho the setting in YTLite is enabled, shorts still appear in home tab.

### Steps to reproduce the issue

1. Enable Hide Shorts
2. Restart 
3. Shorts are still there
![IMG_4920](https://github.com/Balackburn/YTLitePlus/assets/37876797/16b9023e-dd27-4797-bee8-685e7310c811)

![Uploading IMG_4921.png…]()

 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Use Hide Shorts in YTLITE

**Comment by MaartenSomay** [comment]
> Use Hide Shorts in YTLITE

I have it enabled and still doesnt work

**Comment by Balackburn** [comment]
@MaartenSomay Please share a schreenshot
