### ISSUE TITLE
Don’t stay signed in on Google account.

### ISSUE THREAD

**Issue by Faddy96** [Balackburn/YTLitePlus#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.0 Developer Beta 3
- Device model: iPhone 14 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AppDB with own developer account
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 18.28.3-2.3

### Describe the bug

Every time I start the app, I’m not signed in to my Googles account. Logging in and then closing the app results in a logout.

### Steps to reproduce the issue

1. Start the app
2. Sign in
3. Close app
4. Start the app again
5. Account is not signed in.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Can’t remember if I had this issue when using the app in iOS 16.5.1 (c).

**Comment by LenardValdez** [comment]
Even on the latest version I cant stay logged in

**Comment by Balackburn** [comment]
@LenardValdez How did you signed the app

**Comment by LenardValdez** [comment]
@Balackburn just the typical sign in way by tapping the user icon then sign in with email and password

**Comment by LenardValdez** [comment]
@Balackburn my bad my first reply was dumb. I used signulous

**Comment by Balackburn** [comment]
@LenardValdez That’s where the problem come from, entreprise certificate cause problem with sideloading

**Comment by LenardValdez** [comment]
I see. Thank you for the clarification. Damn too bad uyouplus version is so behind thats the knly ytmod that works with signolous

**Comment by LenardValdez** [comment]
Hello I discovered a "fix" for this on signulous. Apparently they provide 2 certs via uuid registrations; 1 is for developer and 1 is for distribution. I used e-sign and used the apple distribution cert and it works!!

**Comment by btglr** [comment]
The same thing happens with me with AppDB. I’m using my own developer account though. Any idea on how to fix it?

**Comment by LenardValdez** [comment]
> The same thing happens with me with AppDB. I’m using my own developer account though. Any idea on how to fix it?

Make sure you have the provisions installed on your device.

**Comment by btglr** [comment]
> > The same thing happens with me with AppDB. I’m using my own developer account though. Any idea on how to fix it?
> 
> Make sure you have the provisions installed on your device. 

Not sure what you mean by provisions in this case, the only thing AppDB requires you to install is their management profile.

**Comment by lloyd0523** [comment]
@btglr Hi just want to say that I had the same problem a few months ago and I figured out it was because some code was deleted that made google account couldn’t stay signed in when installed via AppDB. I created a fork and added back the code and it works fine on my devices. I have some compiled ipas on my fork. You can try them and see if they work.

**Comment by LenardValdez** [comment]
> > > The same thing happens with me with AppDB. I’m using my own developer account though. Any idea on how to fix it?
> > 
> > Make sure you have the provisions installed on your device. 
> 
> Not sure what you mean by provisions in this case, the only thing AppDB requires you to install is their management profile.

Im not sure if appdb provides the .mobileprovision file available to download. if they do, and if their signing functionality allows custom sign, include that file before signing the ipa. Otherwise use esign to to custom sign your ipa so you can include the mobileprovisions

**Comment by btglr** [comment]
I think appdb actually removes the mobileprovision by default. I don't see any option to disable that though. I ended up using Sideloadly as it's always worked before.

**Comment by btglr** [comment]
I can confirm the latest release with the recent commits have fixed the appdb issue! Thanks for the quick fix.
