### ISSUE TITLE
[Bug] “Hide Shorts” does not hide shorts.

### ISSUE THREAD

**Issue by GainingAccess** [Balackburn/YTLitePlus#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.5.1(c)
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Signulous
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v18.28.3-2.3

### Describe the bug

Enabling “Hide Shorts” in YTLite settings does not remove shorts from the homepage
![IMG_3199](https://github.com/Balackburn/YTLitePlus/assets/110878258/15f3e8f6-b72a-4f32-89f0-970a2124efa6)
![IMG_3200](https://github.com/Balackburn/YTLitePlus/assets/110878258/44ede38c-0315-4343-979e-157dde56b3e4)

### Steps to reproduce the issue

1. Enable “Hide Shorts”
2. Restart the app
3. Shorts are still in the homepage.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
@GainingAccess Hello this is strange I don't have this issue could you try with normal YTLite (not YTLitePlus) and if you still have this problem open an issue from the dayanch96 Github instead  download it from here: 

https://github.com/dayanch96/YTLite/releases/tag/v2.3

**Comment by Balackburn** [comment]
@GainingAccess Just released a new version could you test again if you still have the issue? :
https://github.com/Balackburn/YTLitePlus/releases/tag/v18.29.1-2.3

**Comment by GainingAccess** [comment]
okay i’ll go and test it.

**Comment by GainingAccess** [comment]
Unfortunately, I still have the issue on the newer versio 
![IMG_3207](https://github.com/Balackburn/YTLitePlus/assets/110878258/59f5c2bf-cf6b-4187-8456-debbf07e916f)
![IMG_3211](https://github.com/Balackburn/YTLitePlus/assets/110878258/7a953ac2-60cb-43dc-8c28-0c0058eadb58)

**Comment by Balackburn** [comment]
@GainingAccess can you try with normal YTLite (not YTLitePlus) https://github.com/dayanch96/YTLite/releases/tag/v2.3

**Comment by GainingAccess** [comment]
I am using the normal YTLite

I go to Settings > YTLite > Shorts > Disable Short options
![IMG_3212](https://github.com/Balackburn/YTLitePlus/assets/110878258/0f9db948-01b6-4c0b-a0da-21fcb7a93ca9)
![IMG_3213](https://github.com/Balackburn/YTLitePlus/assets/110878258/bf22ab7a-d8ab-41c3-94e9-4d88e83a71b1)
![IMG_3214](https://github.com/Balackburn/YTLitePlus/assets/110878258/3bbc4f46-70bb-4651-8cf3-14c80d957464)
![IMG_3215](https://github.com/Balackburn/YTLitePlus/assets/110878258/c62d6df3-545d-4e80-9165-7bec2bf66bdb)

**Comment by GainingAccess** [comment]
Nevermind, I misunderstood what you are saying, I apologize

**Comment by GainingAccess** [comment]
I'll try it right now.

**Comment by Balackburn** [comment]
@GainingAccess Please open an issue the dayanch96 Github instead, unfortunately I can’t do anything about it

**Comment by GainingAccess** [comment]
Okay, thanks.

**Comment by GainingAccess** [comment]
Just confirmed, its an issue with YTLite itself, I will open an issue there. Thanks for directing me to the right location.
