### ISSUE TITLE
[Bug] VP9 codec not playing certain 720p videos are higher quality when they are suppose to

### ISSUE THREAD

**Issue by SuperAmirhamza** [Balackburn/YTLitePlus#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 17 DB4
- Device model: iPhone 12
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):18.23.3-2.3

### Describe the bug

Basically there’s this one video on YouTube called all saints pure shores it’s been uploaded in 720p using the vp9 codec if the vpn codec isn’t on it will play in lower quality however if it’s played with vp9 on it will play on higher quality however on ytpluslite it’s not seeming to do anything watch all saints pure shores on the normal YouTube app and then compare to ytlite 

### Steps to reproduce the issue

1. Ensure VP9 codec is on
2. Search on all saints pure shores music video and play at max 720p
3. Compare the music video with the official YouTube app

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by SuperAmirhamza** [comment]
One thing yes I have updated couple mins ago to the most recent 18.29.xx update and it is still broken

**Comment by Balackburn** [comment]
@SuperAmirhamza I don't think I can do anything about it and the video doesn't seem to be playing in lower quality for me anyway it's a very small issue as it only affects one video. I will close the issue.
