### ISSUE TITLE
Age restricted videos don’t load

### ISSUE THREAD

**Issue by hiddensea** [Balackburn/YTLitePlus#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:iOS 16.4.1
- Device model:iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...):Scarlet custom cert
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):18.31.3-2.3.1

### Describe the bug

Whenever I try and load an age-restricted video, it doesn’t load, it just endlessly buffers. The recommendations don’t load, the comments DO though

### Steps to reproduce the issue

1.find an age restricted video 
2. Play it
3. Wait

### Are you using the newest version of YTLitePlus? If not, why?

❌ No, I'll explain at the end of the template

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Haven’t updated because I can’t download new .IPA files from github everytime there is an update

**Comment by Balackburn** [comment]
@hiddensea Hello, could you give me a link to age-restricted content so that I can test it myself with the latest version? Thanks

**Comment by Balackburn** [comment]
@hiddensea Also I think Scarlet work with altstore source, it will be easier to update with the source you can add : 
https://raw.githubusercontent.com/Balackburn/YTLitePlusAltstore/main/apps.json

**Comment by EthanBezz** [comment]
> could you give me a link to age-restricted content

Here's one I found: https://www.youtube.com/watch?v=cZaJYDPY-YQ
I also seem to have this issue.

**Comment by Balackburn** [comment]
@EthanBezz I've checked I also have the problem, please open an issue on dayanch96 YTLite's GitHub as the problem is also present on basic YTLite, I guess it's because the app is sideloaded and not the tweak itself, I don't have a jailbroken device to test.

**Comment by hiddensea** [comment]
[apparently it's fine](https://github.com/dayanch96/YTLite/issues/32)

**Comment by hiddensea** [comment]
> @hiddensea Also I think Scarlet work with altstore source, it will be easier to update with the source you can add : 
> 
> https://raw.githubusercontent.com/Balackburn/YTLitePlusAltstore/main/apps.json

Addding sources crashes the app

**Comment by Balackburn** [comment]
@hiddensea strange, also try to enable Settings-> YTLite -> Player -> Skip content warning, it fix the issue for me.

**Comment by EthanBezz** [comment]
> @hiddensea strange, also try to enable Settings-> YTLite -> Player -> Skip content warning, it fix the issue for me.

This fixed the issue for me, too.

**Comment by hiddensea** [comment]
> @hiddensea strange, also try to enable Settings-> YTLite -> Player -> Skip content warning, it fix the issue for me.

Works for me. Thanks for the help
