### ISSUE TITLE
[ BUG ] Hidding Button Option Isn't Working

### ISSUE THREAD

**Issue by abheizthe** [Balackburn/YTLitePlus#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 15.7.6 (19H349)
- Device model: iPhone 6s
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of CercubePlus/YtLitePlus (**latest** or **newest** is **NOT** a version number!): v18.25.1-2.1 

### Describe the bug

Hidding button in Video Control Overlay Option" isn't working
- Hide/ Replace Previous and Next Button
- Hide iSponsorBlock Button in Nav Bar

![88015323-26E4-43C9-837D-393CA55981CE](https://github.com/Balackburn/YTLitePlus/assets/54247318/4a6c3675-7862-4a81-8370-910abaf59358)

![3FDDC628-B3A1-4404-9C8D-06E16C5371EC](https://github.com/Balackburn/YTLitePlus/assets/54247318/1f756d30-26d5-41a9-919e-0562f8b3f93b)

### Steps to reproduce the issue

1. trying to turning on/ off selected and all the settings
2. restarting YouTube app by force closed it
3. 

### Are you using the newest version of CercubePlus? If not, why?

✅ Yes, I'm using the latest version of CercubePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

if possible, please add "Full Screen To The Right Button"

FYI
i have removing some tweaks from the package like; 1. DontEatMyContent. 2. YTUHD. 3. YouTube Dislike Return. 4. YTABConfig

**Comment by Balackburn** [comment]
Thanks, it's fixed but I need to test the fix by doing a new build before closing the issue. 

See commit [7327617](https://github.com/Balackburn/YTLitePlus/commit/73276177f3c74e547d70fbb4321609a97eeb8514)

**Comment by Balackburn** [comment]
Try with this build https://github.com/Balackburn/YTLitePlus/releases/download/v18.25.1-2.1/YTLitePlus_18.25.1_2.1.ipa

**Comment by abheizthe** [comment]
thanks bro, now it's good at all…
![C451CC52-E7D0-4766-8746-F8CDAB85017B](https://github.com/Balackburn/YTLitePlus/assets/54247318/d8139e79-e28a-4312-bb7d-d3e99b75418e)


my mistake is …
![556AF7B5-D8FA-43D9-8D20-C1DDE2BE701D](https://github.com/Balackburn/YTLitePlus/assets/54247318/25d8236e-2de1-4d2a-92c7-c0e92358306e)
just didn't really know if there's available for "Advanced" mode

thank you!
🥳

**Comment by Balackburn** [comment]
@abheizthe Yes the advanced mode is a bit hidden, it would be better if it was more visible but I don't develop this tweak so I won't change it, you can request @dayanch96 to modify it.
