### ISSUE TITLE
Feature Request: Add DeArrow support

### ISSUE THREAD

**Issue by Casuallynoted** [Balackburn/YTLitePlus#30]
Hello!

If possible, I'd love to see this have support for DeArrow, which removes clickbait titles and thumbnails and replaces them with more accurate ones. I'm not sure how feasible this would be to do but thought I should suggest it.

**Comment by Balackburn** [comment]
@Casuallynoted Their is no tweak for DeArrow only a broswer extension I can't add it to YTLitePlus

**Comment by piejanssens** [comment]
https://github.com/pixelomer/DeArrow-iOS

@Balackburn Can you reopen to track?
