### ISSUE TITLE
[Bug] Subtitles gets out of the video when rotating from Portrait to landscape

### ISSUE THREAD

**Issue by Hex67** [Balackburn/YTLitePlus#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

iOS/iPadOS version: 15.7
- Device model: IPad 8th Generation
- Sideload tool (Esign with Developer Certificate)
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.33.3-2.3.1]

### Describe the bug

As Said earlier in the title Subtitles gets out of the video when rotating from Portrait to landscape.
Here’s  a video explaining the bug:

https://github.com/arichorn/uYouPlusExtra/assets/100369493/5e0bc65b-24b3-4fd0-a851-246826019a0b

### Steps to reproduce the issue

1. Play a video (Your screen Should be in Portrait Mode)
2. Turn on Community subtitles
3. Rotate your IPad screen to Landscape. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
You aren't using YTLitePlus but probalbly UYouPlus/UYouPlusExtra, I can't reproduce this bug please open the issue on https://github.com/arichorn/uYouPlusExtra instead
