### ISSUE TITLE
A Video Won't Load Properly 

### ISSUE THREAD

**Issue by AyeCaptian** [Balackburn/YTLitePlus#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.6
- Device model: iphone 11 pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): scarlet
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):  [v18.33.3-2.3.1]

### Describe the bug

 I tried to watch a video on YTliteplus called, How To Torture a Weeb Part 2, and when I opened it lagged and wouldn't show the video and dislikes. It only showed comments and likes.

### Steps to reproduce the issue

1. search, How To Torture a Weeb Part 2, Youtube channel is Cilvanis
2.  Open it
3. look at it

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Alright that's it.

**Comment by Balackburn** [comment]
@AyeCaptian Try to enable Settings-> YTLite -> Player -> Skip content warning, it fix the issue for me.

**Comment by AyeCaptian** [comment]
That fixed it.
