### ISSUE TITLE
Community posts hiding themselves as they appear

### ISSUE THREAD

**Issue by hiddensea** [Balackburn/YTLitePlus#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:16.4.1(a)
- Device model:iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...):Scarlet (Custom cert)
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):18.33.3-2.3.1

### Describe the bug

When scrolling on home or subscriptions, community posts hide themselves and I get sent up the page 0.5 seconds after they show up. Any fix?

### Steps to reproduce the issue

1. Go on home
2. Look at community post
3. Fail to look at post

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Did you enabled Settings -> Gobal settings -> Hide Community Posts (Disables viewing community posts in the app)
This from the Tweak YTNoCommunityPost, disable this option and try again

**Comment by hiddensea** [comment]
> Did you enabled Settings -> Gobal settings -> Hide Community Posts (Disables viewing community posts in the app)
> 
> This from the Tweak YTNoCommunityPost, disable this option and try again

Works thanks (somehow it enabled itself upon installation)
