### ISSUE TITLE
Speed control in video player overlay and fullscreen in Shorts (hide all overlay buttons when tapped)

### ISSUE THREAD

**Issue by baz-za** [Balackburn/YTLitePlus#38]
Just like in uyouplus. You can change speed by just clicking the + and - button which is below the next/previous video button. And fullscreen shorts says it all.

**Comment by baz-za** [comment]
This is a feature request, I recently changed from uyouplusextra to this and this is all I want and I will be satisfied

**Comment by Balackburn** [comment]
Hi, sorry but I won't add the speed HUD, it's a uYou feature I think and I can't add it as a tweak without adding uYou, plus I don't like the addition of the HUD to the video player, for full screen shorts I'll look into it, for now I'll close this issue. Thank you for the suggestions.
