### ISSUE TITLE
 [Request] Volume Gestures Controls

### ISSUE THREAD

**Issue by pelegs29** [Balackburn/YTLitePlus#4]
simple toggle to enable changing the volume of the video simply by dragging your finger in the upper middle part of a playing video.
video demonstraitng the feature :

https://github.com/Balackburn/YTLitePlus/assets/80215741/de4a4948-6ad6-42db-9ead-2fb2bf570529

Thank you very much.

**Comment by Balackburn** [comment]
@pelegs29 Were is this feature from?

**Comment by pelegs29** [comment]
> @pelegs29 Where does this feature come from?

uYou from MiRO92

**Comment by Balackburn** [comment]
@pelegs29 sorry but it will not be added

**Comment by eliliam** [comment]
@Balackburn wondering why you would be opposed to this, especially with the [newly created issue](https://github.com/YTLitePlus/YTLitePlus/issues/273) asking for this very feature once more
