### ISSUE TITLE
[Bug] Replace this with your title

### ISSUE THREAD

**Issue by metaljay** [Balackburn/YTLitePlus#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 17.0
- Device model: iPhone 15 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): APPDB
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 18.35.4-2.3.1

### Describe the bug

Tested using a brand new developer license, the app logs me out after each time the app quits. This appears to be common as another user has reported on appdb too.

### Steps to reproduce the issue

1. Install via APPDB, login, go back to the home screen and the reopen the app - you’ll be logged out 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello this is fixed
