### ISSUE TITLE
Scarlet Repo?

### ISSUE THREAD

**Issue by GainingAccess** [Balackburn/YTLitePlus#42]
Is it possible for you to make a scarlet repo? I use scarlet with my custom certificate and, while altstore repos can load in scarlet, they dont really work well (installed apps will disappear from the installed app list upon restarting). You can find Scarlets repo format here:
https://usescarlet.com/scarlet.json

**Comment by Balackburn** [comment]
@GainingAccess Hello I will look into it later this week no promise

**Comment by Balackburn** [comment]
@GainingAccess Add https://raw.githubusercontent.com/Balackburn/YTLitePlusScarlet/main/scarlet.json ,it's automatically updated with the latest version please let me know if everything works as expected for you then I will close the issue.

**Comment by GainingAccess** [comment]
Unfortunately, the app still disappears from the installed app list. I know this isnt a issue with Scarlet itself because other repos such as CyPwns (https://ipa.cypwn.xyz/scarlet.json) dont have this problem.

**Comment by Balackburn** [comment]
@GainingAccess Strange I used the same strings as the exemple you gave earlier
what app list does it disappear from? You speak about this one? : 

![IMG_3095](https://github.com/Balackburn/YTLitePlus/assets/93828569/f81ad143-6b55-47d1-87fa-e74d12808982)

**Comment by GainingAccess** [comment]
No, I mean this list.
![IMG_3370](https://github.com/Balackburn/YTLitePlus/assets/110878258/fdeadd14-00d9-40e7-82a4-26273ee6ed1c)

**Comment by Balackburn** [comment]
@GainingAccess I don't think the problem is with the repo, maybe it's something with YTLitePlus ipa itself, I can't do more than the source I created that fits the scarlet repo template.

**Comment by GainingAccess** [comment]
Oh, alright, thanks for making the repo!
