### ISSUE TITLE
[Bug] wrong BundleVersion

### ISSUE THREAD

**Issue by bachig26** [Balackburn/YTLitePlus#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 15.7.9
- Device model: iPhone SE 1st Gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): **18.40.01**

### Describe the bug

actual youtube version is `18.40.01` but the version in the app is `18.40.1` which makes it not able to install.

@Balackburn I hope the version number is fixed and re-uploaded again.
I found this issue just now when i tried to update the app via AltStore as the error show in the screenshot below..

From the `.YTLitePlus_18.40.01_2.3.1\Payload\YouTube.app\Info.plist` in the IPA,
```
	<key>CFBundleShortVersionString</key>
	<string>18.40.1</string>
```
```
	<key>CFBundleVersion</key>
	<string>18.40.1</string>
```

### Screenshot (Error)

![IMG_6888](https://github.com/Balackburn/YTLitePlus/assets/96393348/ca4e3b9c-2740-4aa8-aefd-8452102db086)

### Steps to reproduce the issue

1. when you try installing with a [AltStore source](https://github.com/Balackburn/YTLitePlusAltstore/blob/main/apps.json)
2. then you'll see this error.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hi, I don't know why Youtube did this, they labeled the version differently in the app and on the Appstore  
https://apps.apple.com/us/app/youtube-watch-listen-stream/id544007664  

I edited it to 18.40.1 so it should work with Altstore now, could you give it a try and let me know thanks.

**Comment by bachig26** [comment]
> Hi, I don't know why Youtube did this, they labeled the version differently in the app and on the Appstore https://apps.apple.com/us/app/youtube-watch-listen-stream/id544007664

it's really weird.

> I edited it to 18.40.1 so it should work with Altstore now, could you give it a try and let me know thanks.

it works now. thank you 👍
