### ISSUE TITLE
[Bug] Community posts doesn't load

### ISSUE THREAD

**Issue by samuelc02** [Balackburn/YTLitePlus#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iPadOS 16.6
- Device model: iPad Pro 11inch 1st Gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 18.41.2

### Describe the bug

1. When you go to the community posts tab in a channel they will show the community posts but when you tap them they change to other posts, and as soon as you try to scroll they all disappear and won't load anymore. 

2. For community posts featured in the home tab you can view the small thumbnail and text without issue but as soon as you tap on it to go into the post to view the full contents/comments, it will flash the content for 1 second then goes blank and won't load. 

3. All these work normal in the normal YouTube app, I've tried multiple channels, tried reconnecting my WiFi, restarting the app, restarting my iPad, but the issue persists. 

https://github.com/Balackburn/YTLitePlus/assets/78934399/092df0d7-0f2b-425e-8f0a-64439f8f9764

https://github.com/Balackburn/YTLitePlus/assets/78934399/c4634498-089b-4b57-a45f-5e928a25c409

### Steps to reproduce the issue

1. Go to a channel with community posts, go the the community posts tab, click on the posts or try to scroll
2. Find a community post under Recent posts in the home tab (which might not be easy idk when YouTube decides to show them they are not always there), click on the post to view the contents

Videos are attached in the previous section

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello this isn't a bug, uncheck the Settings->General->Hide community posts toggle

**Comment by samuelc02** [comment]
> Hello this isn't a bug, uncheck the Settings->General->Hide community posts toggle

Ok I went and checked the Hide Community Posts setting, it was already Off originally but I tried to toggle it and now the community posts seem to work, but for some reason the toggle is stuck at On and I can't turn it back off, like the settings doesn't save I could toggle it to Off but when I open settings again it will always be at On, and unlike the the other toggles it doesn't show "Your changes have been saved". Despite this the community posts are working fine. I will do some more in depth testing later to see whether I could change the setting.

**Comment by jeffzyliu** [comment]
I'm running into the same issue.

When "hide community posts" is off, the posts disappear as I scroll.

When I turn ON "hide community posts", the posts appear as normal. It almost seems like the switch is backwards; turning on hiding posts shows them, and vice versa.

**Comment by Balackburn** [comment]
> I'm running into the same issue.
> 
> When "hide community posts" is off, the posts disappear as I scroll.
> 
> When I turn ON "hide community posts", the posts appear as normal. It almost seems like the switch is backwards; turning on hiding posts shows them, and vice versa.

@arichorn This is your tweak, do you know where this come from?

**Comment by jeffzyliu** [comment]
> @arichorn This is your tweak, do you know where this come from? 

I want to add that I've used uYouPlus and uYouEnhanced before, and I've never run into this issue before. I don't know what changed to cause this bug in my new YTLitePlus installation.
