### ISSUE TITLE
Hide Shorts Videos Toggle Not working

### ISSUE THREAD

**Issue by pratheek69** [Balackburn/YTLitePlus#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 17
- Device model: 12
- Sideload tool (AltStore, Sideloadly, TrollStore,...):  SideStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v18.41.2-2.3.1

### Describe the bug

The Hide Shorts when turned on 
 shorts section on the HOMEPAGE  still Persists
 while the shorts section in Subscription and Search are removed

### Steps to reproduce the issue

![image](https://github.com/Balackburn/YTLitePlus/assets/79799243/cd41fd48-11eb-48d5-b601-f3d59c98a6f4)
![image](https://github.com/Balackburn/YTLitePlus/assets/79799243/cd7e8e3b-c548-4f8e-9b6d-90a0009d2347)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello I added "Hide Shorts (YTUnShorts)" in YTLitePlus<Miscellaneous, it works with latest YT version
