### ISSUE TITLE
YTLitePlus could not be added to AltStore

### ISSUE THREAD

**Issue by Trung113395** [Balackburn/YTLitePlus#56]
Can u fix it? I have upgraded lastest AltStore (1.7)
My device: iPhone 12
![image](https://github.com/Balackburn/YTLitePlus/assets/64304344/0ff3d019-afa9-43be-9e0c-4aab56a17c5a)

**Comment by Balackburn** [comment]
Hello this is normal as Altstore 1.7 doesn't support custom sources, install Altstore beta :

https://cdn.altstore.io/file/altstore/apps/altstore/2_0_b5.ipa
