### ISSUE TITLE
Shorts Still Showing Up On Homepage After Disabling

### ISSUE THREAD

**Issue by cubcrain** [Balackburn/YTLitePlus#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.1.2
- Device model: MLTP3LL/A
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 2.4

### Describe the bug

Not sure if I'm just missing a setting but I haven't seen anyone else mention that shorts have started appearing recently without something changing. I disabled them for a while and then shorts reappeared, so I updated to the most current IPA and am having the same issue still. Thanks!

![IMG_1467](https://github.com/Balackburn/YTLitePlus/assets/49261928/5715c035-02b0-4108-abf3-22d41967c1c2)
![IMG_1468](https://github.com/Balackburn/YTLitePlus/assets/49261928/4f3caef5-fb99-4eef-a751-a10eb0c68d6e)

### Steps to reproduce the issue

1. Disable Shorts settings in screenshot
2. Restart App
3. Go to homepage, shorts should still appear 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Yes this is known, their is another setting to hide shorts use this toggle instead YTLitePlus>Miscellanous> Hide Shorts (YTUnShorts)
