### ISSUE TITLE
Not turning on “Skip Content Warning” makes videos with content warning not play

### ISSUE THREAD

**Issue by samuelc02** [Balackburn/YTLitePlus#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iPadOS 17.2
- Device model: iPad Pro 11 inch 3rd gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 18.49.3-2.4

### Describe the bug

When Skip Content Warning is turned off, the video with content warning would not play. When it’s turned on, it works fine and skips the content warning.

An additional problem is in both scenarios, the video recommendations on the side bar does not load for videos with content warning. 

The video is too big I can’t upload it, so view it at this link: https://streamable.com/zwpqvk

### Steps to reproduce the issue

1. Find a video with content warning, confirm that on the original Youtube app. 
2. Turn off “skip content warning”
3. Try to play the video, it won’t play. 
4. No video recommendations would load

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello this should be fixed, could you try latest version and tell me if you still have this issue so I can close the issue? Thank you
