### ISSUE TITLE
MrBeastify tweak support

### ISSUE THREAD

**Issue by olivertzeng** [Balackburn/YTLitePlus#63]

**Comment by Balackburn** [comment]
Sorry but I won't add this tweak as I don't think most people will find it usefull in anyway, I saw that you made a fork you can add it yourself if you want.

**Comment by olivertzeng** [comment]
> Sorry but I won't add this tweak as I don't think most people will find it usefull in anyway, I saw that you made a fork you can add it yourself if you want.

Thanks for the reply! But I don't know how I can really add a tweak?

**Comment by Balackburn** [comment]
- 1 Clone your repostory with `git clone -recursive https://github.com/olivertzeng/YTLitePlus.git`
- 2 Open the cloned repostory in your terminal and add the MrBeastify submodule with `git submodule add https://github.com/leminlimez/MrBeastify.git Tweaks/MrBeastify`
- 3 Open the cloned YTLitePlus repostory in VSCode and edit the makefile to add the tweak 
   - Add `.theos/obj/MrBeastify-ObjC.dylib` to the end of the `YTLitePlus_FILES` line
   - Add `Tweaks/MrBeastify` to the end of the `SUBPROJECTS` line
   - Add the line `@cp -R Tweaks/MrBeastify/layout/Library/Application\ Support/MrBeastify.bundle Resources/
` after others `@cp -R` lines
- 4 Push the changes by running`git commit -m "Added the MrBeastify submodule to the project." && git push`
- 5 Build the .ipa with the github actions

**Comment by olivertzeng** [comment]
> - 1 Clone your repostory with `git clone -recursive https://github.com/olivertzeng/YTLitePlus.git`
> 
> - 2 Open the cloned repostory in your terminal and add the MrBeastify submodule with `git submodule add https://github.com/leminlimez/MrBeastify.git Tweaks/MrBeastify`
> 
> - 3 Open the cloned YTLitePlus repostory in VSCode and edit the makefile to add the tweak 
> 
>    - Add `.theos/obj/MrBeastify-ObjC.dylib` to the end of the `YTLitePlus_FILES` line
> 
>    - Add `Tweaks/MrBeastify` to the end of the `SUBPROJECTS` line
> 
>    - Add the line `@cp -R Tweaks/MrBeastify/layout/Library/Application\ Support/MrBeastify.bundle Resources/
> 
> ` after others `@cp -R` lines
> 
> - 4 Push the changes by running`git commit -m "Added the MrBeastify submodule to the project." && git push`
> 
> - 5 Build the .ipa with the github actions

Do I also have to run the update submodules github action?
And I use neovim BTW

**Comment by olivertzeng** [comment]
Thanks for the explanation!

**Comment by olivertzeng** [comment]
> - 1 Clone your repostory with `git clone -recursive https://github.com/olivertzeng/YTLitePlus.git`
> 
> - 2 Open the cloned repostory in your terminal and add the MrBeastify submodule with `git submodule add https://github.com/leminlimez/MrBeastify.git Tweaks/MrBeastify`
> 
> - 3 Open the cloned YTLitePlus repostory in VSCode and edit the makefile to add the tweak 
> 
>    - Add `.theos/obj/MrBeastify-ObjC.dylib` to the end of the `YTLitePlus_FILES` line
> 
>    - Add `Tweaks/MrBeastify` to the end of the `SUBPROJECTS` line
> 
>    - Add the line `@cp -R Tweaks/MrBeastify/layout/Library/Application\ Support/MrBeastify.bundle Resources/
> 
> ` after others `@cp -R` lines
> 
> - 4 Push the changes by running`git commit -m "Added the MrBeastify submodule to the project." && git push`
> 
> - 5 Build the .ipa with the github actions

Shouldn't the dylib path be in INJECT_DYLIBS?

**Comment by olivertzeng** [comment]
> - 1 Clone your repostory with `git clone -recursive https://github.com/olivertzeng/YTLitePlus.git`
> 
> - 2 Open the cloned repostory in your terminal and add the MrBeastify submodule with `git submodule add https://github.com/leminlimez/MrBeastify.git Tweaks/MrBeastify`
> 
> - 3 Open the cloned YTLitePlus repostory in VSCode and edit the makefile to add the tweak 
> 
>    - Add `.theos/obj/MrBeastify-ObjC.dylib` to the end of the `YTLitePlus_FILES` line
> 
>    - Add `Tweaks/MrBeastify` to the end of the `SUBPROJECTS` line
> 
>    - Add the line `@cp -R Tweaks/MrBeastify/layout/Library/Application\ Support/MrBeastify.bundle Resources/
> 
> ` after others `@cp -R` lines
> 
> - 4 Push the changes by running`git commit -m "Added the MrBeastify submodule to the project." && git push`
> 
> - 5 Build the .ipa with the github actions

Done

**Comment by Balackburn** [comment]
> > * 1 Clone your repostory with `git clone -recursive https://github.com/olivertzeng/YTLitePlus.git`
> > * 2 Open the cloned repostory in your terminal and add the MrBeastify submodule with `git submodule add https://github.com/leminlimez/MrBeastify.git Tweaks/MrBeastify`
> > * 3 Open the cloned YTLitePlus repostory in VSCode and edit the makefile to add the tweak
> >   
> >   * Add `.theos/obj/MrBeastify-ObjC.dylib` to the end of the `YTLitePlus_FILES` line
> >   * Add `Tweaks/MrBeastify` to the end of the `SUBPROJECTS` line
> >   * Add the line `@cp -R Tweaks/MrBeastify/layout/Library/Application\ Support/MrBeastify.bundle Resources/
> > 
> > `after others`@cp -R` lines
> > 
> > * 4 Push the changes by running`git commit -m "Added the MrBeastify submodule to the project." && git push`
> > * 5 Build the .ipa with the github actions
> 
> Shouldn't the dylib path be in INJECT_DYLIBS?

Yes it's in YTLitePlus_INJECT_DYLIBS

**Comment by Balackburn** [comment]
> > * 1 Clone your repostory with `git clone -recursive https://github.com/olivertzeng/YTLitePlus.git`
> > * 2 Open the cloned repostory in your terminal and add the MrBeastify submodule with `git submodule add https://github.com/leminlimez/MrBeastify.git Tweaks/MrBeastify`
> > * 3 Open the cloned YTLitePlus repostory in VSCode and edit the makefile to add the tweak
> >   
> >   * Add `.theos/obj/MrBeastify-ObjC.dylib` to the end of the `YTLitePlus_FILES` line
> >   * Add `Tweaks/MrBeastify` to the end of the `SUBPROJECTS` line
> >   * Add the line `@cp -R Tweaks/MrBeastify/layout/Library/Application\ Support/MrBeastify.bundle Resources/
> > 
> > `after others`@cp -R` lines
> > 
> > * 4 Push the changes by running`git commit -m "Added the MrBeastify submodule to the project." && git push`
> > * 5 Build the .ipa with the github actions
> 
> Do I also have to run the update submodules github action? And I use neovim BTW

Yes updates the submodules, and use https://litterbox.catbox.moe for the .ipa upload, some upload don't work

**Comment by olivertzeng** [comment]
> > > * 1 Clone your repostory with `git clone -recursive https://github.com/olivertzeng/YTLitePlus.git`
> 
> > > * 2 Open the cloned repostory in your terminal and add the MrBeastify submodule with `git submodule add https://github.com/leminlimez/MrBeastify.git Tweaks/MrBeastify`
> 
> > > * 3 Open the cloned YTLitePlus repostory in VSCode and edit the makefile to add the tweak
> 
> > >   
> 
> > >   * Add `.theos/obj/MrBeastify-ObjC.dylib` to the end of the `YTLitePlus_FILES` line
> 
> > >   * Add `Tweaks/MrBeastify` to the end of the `SUBPROJECTS` line
> 
> > >   * Add the line `@cp -R Tweaks/MrBeastify/layout/Library/Application\ Support/MrBeastify.bundle Resources/
> 
> > > 
> 
> > > `after others`@cp -R` lines
> 
> > > 
> 
> > > * 4 Push the changes by running`git commit -m "Added the MrBeastify submodule to the project." && git push`
> 
> > > * 5 Build the .ipa with the github actions
> 
> > 
> 
> > Do I also have to run the update submodules github action? And I use neovim BTW
> 
> 
> 
> Yes updates the submodules, and use https://litterbox.catbox.moe for the .ipa upload, some upload services don't work 

Thank god I was just trying to find an upload website

**Comment by olivertzeng** [comment]
@Balackburn ![image](https://github.com/Balackburn/YTLitePlus/assets/86348833/dcc43c7c-720e-422b-8db8-781ef9793ccb) what does that mean?

**Comment by Balackburn** [comment]
> @Balackburn ![image](https://private-user-images.githubusercontent.com/86348833/294215784-dcc43c7c-720e-422b-8db8-781ef9793ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDQ0MzMsIm5iZiI6MTcwNDQwNDEzMywicGF0aCI6Ii84NjM0ODgzMy8yOTQyMTU3ODQtZGNjNDNjN2MtNzIwZS00MjJiLThkYjgtNzgxZWY5NzkzY2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIxMzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMjQ2ZmZjMzU5MzcxMjE5NGQ2NTYyOGM5ZGU1OWJkYTAzNjU0NzIwMzM2ZTg0NzFjMDY2MTExOWUwNmVjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W379GEsBaLJqcX-KrURJ_vW8X49vcUlFIiN4zJ5BKGM) what does that mean?

I don't know, never had this issue myself did you succefully installed the tweak ?

**Comment by olivertzeng** [comment]
> > @Balackburn ![image](https://private-user-images.githubusercontent.com/86348833/294215784-dcc43c7c-720e-422b-8db8-781ef9793ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDQ0MzMsIm5iZiI6MTcwNDQwNDEzMywicGF0aCI6Ii84NjM0ODgzMy8yOTQyMTU3ODQtZGNjNDNjN2MtNzIwZS00MjJiLThkYjgtNzgxZWY5NzkzY2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIxMzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMjQ2ZmZjMzU5MzcxMjE5NGQ2NTYyOGM5ZGU1OWJkYTAzNjU0NzIwMzM2ZTg0NzFjMDY2MTExOWUwNmVjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W379GEsBaLJqcX-KrURJ_vW8X49vcUlFIiN4zJ5BKGM) what does that mean?
> 
> 
> 
> I don't know, never had this issue myself did you succefully installed the tweak ?

Nope

**Comment by Balackburn** [comment]
@olivertzeng I installed the built .ipa succefully with sideloadly and did not found the "MrBeastify" option, I then installed uYouEnhanced because it's supposed to have it and couldn't find the option either, do you know where it's supposed to be located?

**Comment by olivertzeng** [comment]
> @olivertzeng I installed the built .ipa succefully with sideloadly and did not found the "MrBeastify" option, I then installed uYouEnhanced because it's supposed to have it and couldn't find the option either, do you know where it's supposed to be located?

Tweaks/MrBeastify

**Comment by Balackburn** [comment]
@olivertzeng No I wanted to say where is it located in the settings

**Comment by olivertzeng** [comment]
> @olivertzeng No I wanted to say where is it located in the settings

Idk
Haven't even used it yet I'm still very curious about that but I'm using arcihorn's MrBeastify fork
BTW both of you are helpful guys thanks!

**Comment by Balackburn** [comment]
Thank you, I hope it helped

**Comment by olivertzeng** [comment]
> Thank you, I hope it helped

I've never learned swift/Obj-C
But I'll try to real through Settings.x to find them IG

**Comment by olivertzeng** [comment]
> Thank you, I hope it helped

Maybe it was disabled![image](https://github.com/Balackburn/YTLitePlus/assets/86348833/86a2f3a6-db79-4855-ab69-af9f54b6984c)

**Comment by Balackburn** [comment]
> > Thank you, I hope it helped
> 
> Maybe it was disabled![image](https://private-user-images.githubusercontent.com/86348833/294324307-86a2f3a6-db79-4855-ab69-af9f54b6984c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTAxMTksIm5iZiI6MTcwNDQ0OTgxOSwicGF0aCI6Ii84NjM0ODgzMy8yOTQzMjQzMDctODZhMmYzYTYtZGI3OS00ODU1LWFiNjktYWY5ZjU0YjY5ODRjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxMDE2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDk4NWFmYjA1MTVjMDM3MmJkZGU0YjNmYjkyMDdkYzQ1ZGVkY2JkNTVmZDMwNDNmODBiNzQ2NmMyZmVmMGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ifhe2GMix9ls4B76GpdVRw_4igmM5RalT9IyXKbw8Ac)

It doesn't work (broken) with latest Youtube version, try with an old version

**Comment by olivertzeng** [comment]
> > > Thank you, I hope it helped
> 
> > 
> 
> > Maybe it was disabled![image](https://private-user-images.githubusercontent.com/86348833/294324307-86a2f3a6-db79-4855-ab69-af9f54b6984c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTAxMTksIm5iZiI6MTcwNDQ0OTgxOSwicGF0aCI6Ii84NjM0ODgzMy8yOTQzMjQzMDctODZhMmYzYTYtZGI3OS00ODU1LWFiNjktYWY5ZjU0YjY5ODRjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxMDE2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDk4NWFmYjA1MTVjMDM3MmJkZGU0YjNmYjkyMDdkYzQ1ZGVkY2JkNTVmZDMwNDNmODBiNzQ2NmMyZmVmMGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ifhe2GMix9ls4B76GpdVRw_4igmM5RalT9IyXKbw8Ac)
> 
> 
> 
> It doesn't work (broken) with latest Youtube version, try with an old version

Ok

**Comment by olivertzeng** [comment]
> > > Thank you, I hope it helped
> 
> > 
> 
> > Maybe it was disabled![image](https://private-user-images.githubusercontent.com/86348833/294324307-86a2f3a6-db79-4855-ab69-af9f54b6984c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTAxMTksIm5iZiI6MTcwNDQ0OTgxOSwicGF0aCI6Ii84NjM0ODgzMy8yOTQzMjQzMDctODZhMmYzYTYtZGI3OS00ODU1LWFiNjktYWY5ZjU0YjY5ODRjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxMDE2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDk4NWFmYjA1MTVjMDM3MmJkZGU0YjNmYjkyMDdkYzQ1ZGVkY2JkNTVmZDMwNDNmODBiNzQ2NmMyZmVmMGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ifhe2GMix9ls4B76GpdVRw_4igmM5RalT9IyXKbw8Ac)
> 
> 
> 
> It doesn't work (broken) with latest Youtube version, try with an old version

Which version?

**Comment by Balackburn** [comment]
IDK you can try with a version from 3 month ago as the tweak was last updated

**Comment by olivertzeng** [comment]
> IDK you can try with a version from 3 month ago as the tweak was last updated 

Ok got it working by installing the tweak itself(since I'm on Kfd)![image](https://github.com/Balackburn/YTLitePlus/assets/86348833/3dc0a4af-66db-4cd8-b28c-ec568de85af7)![image](https://github.com/Balackburn/YTLitePlus/assets/86348833/1493fc22-602b-4725-a15c-358a1d4fbece)
The settings are here if u want

**Comment by olivertzeng** [comment]
> > > IDK you can try with a version from 3 month ago as the tweak was last updated
> > 
> > 
> > Ok got it working by installing the tweak itself(since I'm on Kfd)
> > The settings are here if u want
> 
> Wait it actually works? This seems interesting.. 🤔

It did
