### ISSUE TITLE
[Bug] No “Player” option in YTLite - Cannot bypass content warning

### ISSUE THREAD

**Issue by acryllect** [Balackburn/YTLitePlus#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.0
- Device model: iPhone 14
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Trollstore 2, Altstore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 18.48.3-2.4

### Describe the bug

I read that to bypass the issue with age restricted videos (#28 i believe) I should go to Settings -> YTLite -> Player and enable “skip content warning”, but I do not seem to have the Player section.

![IMG_2089](https://github.com/Balackburn/YTLitePlus/assets/46241219/3ff7f4fb-54c6-4a99-b7cc-e81525fadbdb)

Clicking on the blank space does nothing.

### Steps to reproduce the issue

I just installed the app. I tried older versions before this one too.

### Are you using the newest version of YTLitePlus? If not, why?

❌ No, I'll explain at the end of the template

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

I’ve been having this issue since i first installed the app, i’m not sure if i have the latest version or not, but until now updating has not solved it.

**Comment by Balackburn** [comment]
Activate the advanced settings, click on version and enable it
