### ISSUE TITLE
[Bug] Shorts Filter Shows Nothing When Searching

### ISSUE THREAD

**Issue by huandney** [Balackburn/YTLitePlus#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.2.1
- Device model: iPhone 15 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): appdb
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.01.1-2.4

### Describe the bug

When Searching Any Topic in the Search Bar and Clicking on the Shorts Filter, Nothing Is Displayed.

![IMG_0364](https://github.com/Balackburn/YTLitePlus/assets/19948348/a3496eea-4cbf-4b82-9441-6b2ef3183d5d)

### Steps to reproduce the issue

1. Search for any term
2. Click on Shorts at the top

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello I tested with latest version and this bug is no more, could you try and tell me if it's good for you so I can close the issue? Thank you

**Comment by huandney** [comment]
It's working well now. Thanks.
