### ISSUE TITLE
Cannot find YTNoSuggestedVideo on v19.01.1-2.4 anywhere in the YTLitePlus settings

### ISSUE THREAD

**Issue by kevin-hub2020** [Balackburn/YTLitePlus#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.6.1
- Device model: iPad Pro (11-inch) (2nd generation)
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Trollstore 2.0.11
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.01.1-2.4

### Describe the bug

Cannot find YTNoSuggestedVideo on v19.01.1-2.4 anywhere in the YTLitePlus settings
I tried to look for it under the flags but is not there. Please specify where it is.

### Steps to reproduce the issue

1. Look for the setting YTNoSuggestedVideo
2. Cannot be found

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Settings<YTLitePlus<Video Controls Overlay Options<Hide suggested Video (YTNoSuggestedVideo)
