### ISSUE TITLE
Show Quality Button (Bottom) not working

### ISSUE THREAD

**Issue by MaartenSomay** [Balackburn/YTLitePlus#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.1.2
- Device model: Ip 14 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Esign
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.02.1

### Describe the bug

Video Overlay - Show Quality Button - Bottom

Quality option is not showing, this worked on all previous versions. It should show up right next to the full screen button. Top option works.

### Steps to reproduce the issue

1.  Video Overlay
2. Show Quality Button
3. Bottom

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello, I made a new build that fix this, reinstall the latest version 
https://github.com/Balackburn/YTLitePlus/releases/download/v19.02.1-2.4/YTLitePlus_19.02.1_2.4.ipa

**Comment by MaartenSomay** [comment]
> Hello, I made a new build that fix this, reinstall the latest version https://github.com/Balackburn/YTLitePlus/releases/download/v19.02.1-2.4/YTLitePlus_19.02.1_2.4.ipa

Perfect thanks! Works great now🙌
