### ISSUE TITLE
[Bug] Settings crash

### ISSUE THREAD

**Issue by backstab5983** [Balackburn/YTLitePlus#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.3
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): [v19.03.2-2.4.1 - YTLitePlus](https://github.com/Balackburn/YTLitePlus/releases/tag/v19.03.2-2.4.1)

### Describe the bug

Every time I click on settings the app just crashes. 

### Steps to reproduce the issue

1.  Open YT app
2.  Click on settings
3.  App crashes

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello reinstall the latest .ipa I made a new build this is fixed

**Comment by Balackburn** [comment]
https://github.com/Balackburn/YTLitePlus/releases/download/v19.03.2-2.4.1/YTLitePlus_19.03.2_2.4.1.ipa

**Comment by Balackburn** [comment]
https://github.com/Balackburn/YTLitePlus/commit/6174f45f3c4afd1f8248d4e228d66df4706e20f2
