### ISSUE TITLE
[Bug] Return YouTube Dislike error

### ISSUE THREAD

**Issue by huandney** [Balackburn/YTLitePlus#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.3
- Device model: iPhone 15 pro 
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.03.2-2.4.1

### Describe the bug

The amount of likes and dislikes is always the same.

### Steps to reproduce the issue

![IMG_0502](https://github.com/Balackburn/YTLitePlus/assets/19948348/c97f79b7-b2db-46c6-9734-02ff9a5ca075)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello it happens because Youtube Return Dislike API is down, this is universal (Chrome/Firefox Extensions /Userscript)

https://github.com/Anarios/return-youtube-dislike/issues/1029

https://returnyoutubedislikeapi.com/votes?videoId=

It doesn't come from the tweak and will be fixed when it's back
