### ISSUE TITLE
Shorts Progress Bar doesn't always show

### ISSUE THREAD

**Issue by Uwe5000** [Balackburn/YTLitePlus#76]
Surely the option for the progress bar is enabled in settings, but unfortunately it doesn't always show up. 
Sometimes, when it doesn't show up, it comes back when you press pause.

**Comment by Balackburn** [comment]
Hello it should now work correctly could you try v19.06.2-2.5 and tell me if it work for you so I can close the issue. Thank you

**Comment by Uwe5000** [comment]
Solved!
Thxx
