### ISSUE TITLE
[Bug] Homepage keeps showing “Something went wrong”

### ISSUE THREAD

**Issue by ableabhinav** [Balackburn/YTLitePlus#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.2.1
- Device model: Iphone 11 pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Signed using a developer certificate and installed on the phone using apple configurator.
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):
19.05.3_2.4.1

### Describe the bug

Since today I keep getting “Something went wrong” on the homepage as the title suggests. Also attaching a photo for reference.

Please let me know what can be done to solve this issue.

Thanks
![IMG_2029](https://github.com/Balackburn/YTLitePlus/assets/20612530/c678a68a-29b6-487e-be1c-83aafbcc4413)

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

❌ No, I'll explain at the end of the template

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello did it just appeared and worked before or did you changed a setting / installed a different version?
I haven't encountered this bug myself, you can try installing the latest version and see if that fixes it.

**Comment by Balackburn** [comment]
Hello this seem to appear on 19.05.3_2.4.1 but not 19.06.2_2.4.1

**Comment by Yterz** [comment]
I had the same issue : working yesterday on 19.05.3_2.4.1, and this morning same no connection error for all tab, without any change. Only the google account setting was properly responding.

Updating to 19.06.2_2.4.1 fixed it, it's back to working as usual.

**Comment by chaunceyhui** [comment]
I'm using sidestore to update, but it is showing 19.05.3 and not the latest release 19.06.2. Any idea why this is happening? I updated to 19.05.3 and was having same issue as above, but sidestore didn't have an option to update to the latest.

**Comment by Balackburn** [comment]
> I'm using sidestore to update, but it is showing 19.05.3 and not the latest release 19.06.2. Any idea why this is happening? I updated to 19.05.3 and was having same issue as above, but sidestore didn't have an option to update to the latest.

Yes their is a bug with Sidestore not showing the latest update or not allowing to update to the latest version (not showing an "update" badge and button) 

The solution is to remove the source, re-add it and install it by clicking on the "free" badge, it will update it to the latest version.

**Comment by ableabhinav** [comment]
Ok I installed the latest version. Seems to be working fine now. Thanks

**Comment by Balackburn** [comment]
I am closing the issue as this was specific to [19.05.3](https://github.com/Balackburn/YTLitePlus/releases/tag/v19.05.3-2.4.1)
