### ISSUE TITLE
[Bug] YouTube crashes when trying to open a video

### ISSUE THREAD

**Issue by seewhyjay** [Balackburn/YTLitePlus#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.3.1
- Device model: iPhone 15 Plus
- Sideload tool (AltStore, Sideloadly, TrollStore,...): ESign
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.06.2-2.4.1

### Describe the bug

Trying to open a video crashes youtube immediately.
I had this issue with [v19.05.3-2.4.1](https://github.com/Balackburn/YTLitePlus/releases/tag/v19.05.3-2.4.1) too. The last working version for me that doesn't cause this crash is 19.03.2.

https://github.com/Balackburn/YTLitePlus/assets/57669931/1c52605a-1932-4c1b-b132-d96b8b01bade

### Steps to reproduce the issue

1. Open YouTube
2. Open a video
3. 

### Crash log (if the app crashes)

[YouTube-2024-02-15-231800.txt](https://github.com/Balackburn/YTLitePlus/files/14298725/YouTube-2024-02-15-231800.txt)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello thank you for posting this issue, I don't have this problem myself but from the crash log it seem that you edited the BundleId to com.google.ios.youtubeplus this would be one thing that is different from my installation and could potentially cause issues, I am going to do an identical installation as you (ESign and edited bundle id) later this day to see if it results in the same crash.

**Comment by seewhyjay** [comment]
Thanks for trying to help! In that case I'll just downgrade and hopefully a later update fixes this issue.

**Comment by degen91** [comment]
I have an iPhone SE 2020 on iOS 17.3.1. My sideload tool is Sideloadly. I had this issue with v19.05.3-2.4.1 and v19.06.2-2.4.1, but with the latest version as of writing, v19.06.2-2.5, I am no longer experiencing crashes upon opening a video.

**Comment by Balackburn** [comment]
> I have an iPhone SE 2020 on iOS 17.3.1. My sideload tool is Sideloadly. I had this issue with v19.05.3-2.4.1 and v19.06.2-2.4.1, but with the latest version as of writing, v19.06.2-2.5, I am no longer experiencing crashes upon opening a video.

I don't know why but 19.05.3-2.4.1 was bugged, I close the issue by now.
