### ISSUE TITLE
v19.07.4-2.6.1 crashing on open

### ISSUE THREAD

**Issue by garshmo** [Balackburn/YTLitePlus#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS 17.3.1
- Device model: iphone 13 pro
- Sideload tool - Sideloady
- v19.07.4-2.6.1

### Describe the bug

Crashing a second after opening

### Steps to reproduce the issue

1. open app
2. crashes

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Strange, I have almost the same setup as you do myself an iPhone 13 Pro on iOS 17.4 and the app work as expected.

Maybe this is from the decrypted YouTube .ipa I used, I will do another build with a different Youtube .ipa that I decrypted myself later this day to see if it fix it and do some testing.

**Comment by Balackburn** [comment]
Hello fixed on latest version
