### ISSUE TITLE
[BUG]I can't login to my new Youtube account in v19.08.2-2.6.3

### ISSUE THREAD

**Issue by Cy9oz** [Balackburn/YTLitePlus#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:17.4
- Device model: iphone15
- Sideload tool (AltStore, Sideloadly, TrollStore,...):Altstore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):latest

### Describe the bug

I can't log in to my new Youtube account with v19.08.2-2.6.3.
When I try to log in with uYouLogin v2.2, it says "We couldn't verify the security of your Youtube account." and I can't log in.

Steps to reproduce

### Steps to reproduce the issue

Log in to your Youtube account with v19.08.2-2.6.3

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello I removed this release as it wasn't clean, please use the latest version and tell me if you still have this issue : 

https://github.com/Balackburn/YTLitePlus/releases/tag/v19.08.2-2.7

**Comment by Macleykun** [comment]
> Hello I removed this release as it wasn't clean, please use the latest version and tell me if you still have this issue :
> 
> https://github.com/Balackburn/YTLitePlus/releases/tag/v19.08.2-2.7

Assuming they haven't responded in a while, maybe it's best to close the issue?

**Comment by Balackburn** [comment]
@Macleykun I think this issue is still present, I close as it's a duplicate
