### ISSUE TITLE
[Bug] Build fail

### ISSUE THREAD

**Issue by backstab5983** [Balackburn/YTLitePlus#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): [v19.09.4-3.0.1](https://github.com/Balackburn/YTLitePlus/releases/tag/v19.09.4-3.0.1)

### Describe the bug

Following the steps outlined in: https://github.com/qnblackcat/uYouPlus/wiki/Building

I always get the error

`Process completed with exit code 9.`

More specifically in the `Prepare Youtube iPA` part.

Here it is:

```Run wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
  wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
  echo -e "==> \033[1mYouTube v19.09.4 downloaded! \033[0m"
  unzip -q main/YouTube.ipa -d main/tmp
  rm -rf main/tmp/Payload/YouTube.app/_CodeSignature/CodeResources
  rm -rf main/tmp/Payload/YouTube.app/PlugIns/*
  cp -R main/Extensions/*.appex main/tmp/Payload/YouTube.app/PlugIns
  echo -e "==> \033[1mYouTube v19.09.4 unpacked! \033[0m"
  shell: /bin/bash -e {0}
  env:
    THEOS: /Users/runner/work/YTLitePlus/YTLitePlus/theos
    YOUTUBE_VERSION: 19.09.4
    YOUTUBE_URL: REDACTED
[2](https://github.com/backstab5983/YTLitePlus/actions/runs/8194210058/job/22409723603#step:9:2)024-0[3](https://github.com/backstab5983/YTLitePlus/actions/runs/8194210058/job/22409723603#step:9:3)-07 20:13:50 URL:https://drive.google.com/file/d/1[4](https://github.com/backstab5983/YTLitePlus/actions/runs/8194210058/job/22409723603#step:9:4)lCfo4[5](https://github.com/backstab5983/YTLitePlus/actions/runs/8194210058/job/22409723603#step:9:5)Zyjw30oNRxOxJ0[7](https://github.com/backstab5983/YTLitePlus/actions/runs/8194210058/job/22409723603#step:9:7)[8](https://github.com/backstab5983/YTLitePlus/actions/runs/8194210058/job/22409723603#step:9:8)3_WD3pRZl/view?usp=sharing [87150] -> "main/YouTube.ipa" [1]
==> YouTube v1[9](https://github.com/backstab5983/YTLitePlus/actions/runs/8194210058/job/22409723603#step:9:9).09.4 downloaded! 
[main/YouTube.ipa]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of main/YouTube.ipa or
        main/YouTube.ipa.zip, and cannot find main/YouTube.ipa.ZIP, period.
Error: Process completed with exit code 9.
```

I redacted the Google Drive link I used but I tried both sharing a link direct to the YouTube .ipa and also to a .zip archive containing the .ipa.

### Steps to reproduce the issue

1. Try to build the app using Google Drive link
2. Encounter error

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Are you sure you are using a decrypted .ipa? 
Also myself I use https://litterbox.catbox.moe to upload it, some cloud storage service doesn't allow direct download. 

The problem come from you not YTLitePlus, I am closing the issue please try again it will work.

**Comment by Balackburn** [comment]
Perfecto 👌
