### ISSUE TITLE
In-player video settings bug

### ISSUE THREAD

**Issue by hzozo** [Balackburn/YTLitePlus#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 17.4
- Device model: iPhone 15 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Signulous
- The specific version of YTLitePlus: 19.10.5-3.01

### Describe the bug

The settings menu in the video player does not equal to the official app, furthermore the ‘Additional settings’ submenu does not load. Under the option ‘Additional settings’ there are three more options with different font sizes as well, feels like some bug. I don’t have version spoofing enabled.

### Steps to reproduce the issue

1. Open any video after installation and an app restart, default settings suffice for me
2. Open the settings
3.  [menu](![Screenshot 2024-03-13 at 22 54 28](https://github.com/Balackburn/YTLitePlus/assets/6569992/74795fc3-a9d4-498e-9ed5-06f5f3e911ff))
4. Click on additional settings, nothing should happen

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Let me know if you need more info. Thank you!

**Comment by Balackburn** [comment]
Hello I was unable to reproduce your issue on a fresh install with default settings here the additionnal settings :

![IMG_3689](https://github.com/Balackburn/YTLitePlus/assets/93828569/7d8596b8-c494-4b6e-8783-ddbba383c231)

**Comment by hzozo** [comment]
Hmm, thank you for checking, especially so quickly!
I've been wondering if this issue was specific to my device, my deployment, I suspect there must be some garbage cache in the data store left over from other YouTube forks or previous versions (after all, login only worked for me by installing uYouPlus, logging in there, uninstalling then installing this).
Surprisingly, after about a week, the issue disappeared on my end this morning, the bottom 3 options with the different font sizes disappeared from the menu and Additional Settings load as well now.

Marking it as resolved, it was some weird iOS not being such a great, secure OS glitch. Thanks again!
