### ISSUE TITLE
Shorts overlay settings don’t apply

### ISSUE THREAD

**Issue by Uwe5000** [Balackburn/YTLitePlus#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.3 Dopamine
- Device model: iPhone XR 
- Sideload tool: TrollStore
- The specific version of YTLitePlus: 3.0.1

### Describe the bug

the player overlay options for Shorts don’t apply 
(like disable search, three dots, remix etc.)

### Steps to reproduce the issue

Use it

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Awesome work ♥️

**Comment by Balackburn** [comment]
Hi, thanks, I'd like to point out that most of the work is not mine as this app is using various tweaks from various developers notably dayanch96, Poomsmart, arichornlover,  qnblackcat and many others.

These options come from the YTLite tweak, not from the YTLitePlus section. Please open an issue on YTLite Github instead.
https://github.com/dayanch96/YTLite/issues

**Comment by Uwe5000** [comment]
Thank you
