### ISSUE TITLE
Shorts player overlay YTLitePlus issue

### ISSUE THREAD

**Issue by Uwe5000** [Balackburn/YTLitePlus#96]
iOS 16.3 Dopamine 
YouTube 19.10.5

Me again
Dayanch96 says only YTLite without other tweaks works, so it should be a YTLitePlus issue
YouTube 19.08.2 / YTLitePlus 2.7 it works for example
I just testet latest appstore YouTube + YTLite (only) it works

**Comment by Uwe5000** [comment]
Does it work for you?

**Comment by Balackburn** [comment]
@Uwe5000 My bad will look into it, why did you closed the issue ?

**Comment by Balackburn** [comment]
@Uwe5000 Did you tried to sideload YTLite .ipa (not installing the tweak on the appstore Youtube ?) 
Maybe the issue is only present when sideloading, I don't see why any of the tweaks present in YTLitePlus would break theses options.
